name: ondrej-mach-tests
on: [push]
jobs:
  test:
    name: Output check (validate program outputs)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build binary
        run: make

      - name: Run tests
        run: python3 ondrej-mach-tests.py
